### ISSUE TITLE
About Paper

### ISSUE THREAD

**Issue by xcfcode** [JianGuanTHU/CommonsenseStoryGen#1]
Hi, Would it be convenient to provide a preprinted version of the paper?

**Comment by JianGuanTHU** [comment]
Sure, it will be made public soon.

**Comment by JianGuanTHU** [comment]
> Hi, Would it be convenient to provide a preprinted version of the paper?

**Comment by JianGuanTHU** [comment]
Sure, it will be made public soon.

**Comment by xcfcode** [comment]
Thanks a lot!

**Comment by xcfcode** [comment]
Hi, where can I find the paper?

**Comment by JianGuanTHU** [comment]
Thank you for your attention. But we are planning to remove the repo under a public account [thu_coai](https://github.com/thu-coai). We will preprint the paper once we prepare the new repo and update the link in the paper.

**Comment by xcfcode** [comment]
Thanks!
